services:
  daemon:
    image: olvid/bot-daemon:2.0.0-alpha
    environment:
      - OLVID_ADMIN_CLIENT_KEY_CLI=RANDOMVALUE
    volumes:
      - ./data:/daemon/data
    ports:
      - "50051:50051"
    networks:
      - olvid_bots_network

  cli:
    image: olvid/bot-python-runner:2.0.0-alpha
    entrypoint: "olvid-cli"
    environment:
      - OLVID_ADMIN_CLIENT_KEY=RANDOMVALUE
      - OLVID_DAEMON_TARGET=daemon:50051
    stdin_open: true
    tty: true
    profiles: ["cli"]
    volumes:
    - ./evelyne/meteo_logo.png:/user_data/meteo_logo.png:ro
    networks:
      - olvid_bots_network

  evelyne:
    image: olvid/bot-python-runner:2.0.0-alpha
    environment:
      - OLVID_CLIENT_KEY=EVELYNE_CLIENT_KEY
      - OLVID_DAEMON_TARGET=daemon:50051
    volumes:
      - ./evelyne:/app:ro
    depends_on:
      - daemon
    networks:
      - olvid_bots_network

networks:
  olvid_bots_network:
    driver: bridge