services:
  olvid-tchouchou-test:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    env_file: .env
    restart: unless-stopped
    networks:
      - olvid-bots_olvid_bots_network

networks:
  olvid-bots_olvid_bots_network:
    external: true